version: "3"

services:
  app:
    container_name: barber-api
    build: .
    ports:
      - 8080:8080
    volumes:
      - ".:/api"
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongo:
    container_name: "barber_mongodb"
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
      - "./.docker/mongo:/data/db"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
